query/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('query', views.query, name='query'),
]

search/models.py
from django.db import models


class LeadRocks(models.Model):
    linked_url = models.CharField(max_length=255)
    full_name = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    job_title = models.CharField(max_length=255)
    facebook_profile = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    company_website = models.CharField(max_length=255)
    company_facebook = models.CharField(max_length=255)
    company_email = models.CharField(max_length=255)
    company_phone = models.CharField(max_length=255)
    industry = models.CharField(max_length=255)
    team_size = models.CharField(max_length=255)
    revenue_range = models.CharField(max_length=255)
    total_funding = models.CharField(max_length=255)
    work_email_1 = models.CharField(max_length=255)
    work_email_1_status = models.CharField(max_length=255)
    direct_email_1 = models.CharField(max_length=255)
    direct_email_1_status = models.CharField(max_length=255)
    direct_email_2 = models.CharField(max_length=255)
    direct_email_2_status = models.CharField(max_length=255)
    phone_1 = models.CharField(max_length=255)
    phone_2 = models.CharField(max_length=255)
    phone_3 = models.CharField(max_length=255)
    phone_4 = models.CharField(max_length=255)
    phone_5 = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.linked_url

search/views.py
from django.shortcuts import render
from .models import LeadRocks


def index(request):
    data = {
        'leadrocks': LeadRocks.objects.all()
    }
    return render(request, 'search/index.html', data)


def query(request):
    d = request.GET

    # query_data = set()
    leadrocks = None

    # ===================================
    full_name = d.get('full_name')
    if full_name:
        if not leadrocks:
            leadrocks = LeadRocks.objects.filter(
                full_name__icontains=full_name)
        else:
            leadrocks = leadrocks.filter(full_name__icontains=full_name)

    # ===================================
    first_name = d.get('first_name')
    if first_name:
        if not leadrocks:
            leadrocks = LeadRocks.objects.filter(
                first_name__icontains=first_name)
        else:
            leadrocks = leadrocks.filter(first_name__icontains=first_name)

    # ===================================
    last_name = d.get('last_name')
    if last_name:
        if not leadrocks:
            leadrocks = LeadRocks.objects.filter(
                last_name__icontains=last_name)
        else:
            leadrocks = leadrocks.filter(last_name__icontains=last_name)

    # ===================================
    job_title = d.get('job_title')
    if job_title:
        if not leadrocks:
            leadrocks = LeadRocks.objects.filter(
                job_title__icontains=job_title)
        else:
            leadrocks = leadrocks.filter(job_title__icontains=job_title)

    data = {
        'leadrocks': leadrocks
    }
    return render(request, 'search/query.html', data)

search/templates/search/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    <div class="">

        <div class="row">

            <div class="col">

                <table class="table table-striped my-5">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Linked Url</th>
                            <th scope="col">Full Name</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Job Title</th>
                            <th scope="col">Facebook Profile</th>
                            <th scope="col">Location</th>
                            <th scope="col">Company</th>
                            <th scope="col">Company Website</th>
                            <th scope="col">Company Facebook</th>
                            <th scope="col">Company Email</th>
                            <th scope="col">Company Phone</th>
                            <th scope="col">Industry</th>
                            <th scope="col">Team Size</th>
                            <th scope="col">Revenue Range</th>
                            <th scope="col">Total Funding</th>
                            <th scope="col">Work Email #1</th>
                            <th scope="col">Work Email #1 Status</th>
                            <th scope="col">Direct Email #1</th>
                            <th scope="col">Direct Email #1 Status</th>
                            <th scope="col">Direct Email #2</th>
                            <th scope="col">Direct Email #2 Status</th>
                            <th scope="col">Phone #1</th>
                            <th scope="col">Phone #2</th>
                            <th scope="col">Phone #3</th>
                            <th scope="col">Phone #4</th>
                            <th scope="col">Phone #5</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for leadrock in leadrocks %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{leadrock.linked_url}}</td>
                            <td>{{leadrock.full_name}}</td>
                            <td>{{leadrock.first_name}}</td>
                            <td>{{leadrock.last_name}}</td>
                            <td>{{leadrock.job_title}}</td>
                            <td>{{leadrock.facebook_profile}}</td>
                            <td>{{leadrock.location}}</td>
                            <td>{{leadrock.company}}</td>
                            <td>{{leadrock.company_website}}</td>
                            <td>{{leadrock.company_facebook}}</td>
                            <td>{{leadrock.company_email}}</td>
                            <td>{{leadrock.company_phone}}</td>
                            <td>{{leadrock.industry}}</td>
                            <td>{{leadrock.team_size}}</td>
                            <td>{{leadrock.revenue_range}}</td>
                            <td>{{leadrock.total_funding}}</td>
                            <td>{{leadrock.work_email_1}}</td>
                            <td>{{leadrock.work_email_1_status}}</td>
                            <td>{{leadrock.direct_email_1}}</td>
                            <td>{{leadrock.direct_email_1_status}}</td>
                            <td>{{leadrock.direct_email_2}}</td>
                            <td>{{leadrock.direct_email_2_status}}</td>
                            <td>{{leadrock.phone_1}}</td>
                            <td>{{leadrock.phone_2}}</td>
                            <td>{{leadrock.phone_3}}</td>
                            <td>{{leadrock.phone_4}}</td>
                            <td>{{leadrock.phone_5}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>


</body>

</html>

search/templates/search/query.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <title>Query page</title>
</head>

<body>

    <div class="container">
        <h1 class="my-2">Query page <a href="{% url 'search:index' %}">Data page</a> </h1>
    </div>

    <div class="container">
        <form method="GET" action="{% url 'search:query' %}">
            <div class="row g-2">
                <div class="col-3">
                    <label for="formGroupExampleInput">Full Name</label>
                    <input type="text" class="form-control" id="full_name" name="full_name" placeholder="Full Name">
                </div>

                <div class="col-3">
                    <label for="formGroupExampleInput2">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name">
                </div>

                <div class="col-3">
                    <label for="formGroupExampleInput2">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name">
                </div>

                <div class="col-3">
                    <label for="formGroupExampleInput2">Job Title</label>
                    <input type="text" class="form-control" id="job_title" name="job_title" placeholder="Job Title">
                </div>

            </div>

            <button type="submit" class="btn btn-success my-3">Do query</button>
        </form>
    </div>

    <div class="">

        <div class="row">

            <div class="col">

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Linked Url</th>
                            <th scope="col">Full Name</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Job Title</th>
                            <th scope="col">Facebook Profile</th>
                            <th scope="col">Location</th>
                            <th scope="col">Company</th>
                            <th scope="col">Company Website</th>
                            <th scope="col">Company Facebook</th>
                            <th scope="col">Company Email</th>
                            <th scope="col">Company Phone</th>
                            <th scope="col">Industry</th>
                            <th scope="col">Team Size</th>
                            <th scope="col">Revenue Range</th>
                            <th scope="col">Total Funding</th>
                            <th scope="col">Work Email #1</th>
                            <th scope="col">Work Email #1 Status</th>
                            <th scope="col">Direct Email #1</th>
                            <th scope="col">Direct Email #1 Status</th>
                            <th scope="col">Direct Email #2</th>
                            <th scope="col">Direct Email #2 Status</th>
                            <th scope="col">Phone #1</th>
                            <th scope="col">Phone #2</th>
                            <th scope="col">Phone #3</th>
                            <th scope="col">Phone #4</th>
                            <th scope="col">Phone #5</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for leadrock in leadrocks %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{leadrock.linked_url}}</td>
                            <td>{{leadrock.full_name}}</td>
                            <td>{{leadrock.first_name}}</td>
                            <td>{{leadrock.last_name}}</td>
                            <td>{{leadrock.job_title}}</td>
                            <td>{{leadrock.facebook_profile}}</td>
                            <td>{{leadrock.location}}</td>
                            <td>{{leadrock.company}}</td>
                            <td>{{leadrock.company_website}}</td>
                            <td>{{leadrock.company_facebook}}</td>
                            <td>{{leadrock.company_email}}</td>
                            <td>{{leadrock.company_phone}}</td>
                            <td>{{leadrock.industry}}</td>
                            <td>{{leadrock.team_size}}</td>
                            <td>{{leadrock.revenue_range}}</td>
                            <td>{{leadrock.total_funding}}</td>
                            <td>{{leadrock.work_email_1}}</td>
                            <td>{{leadrock.work_email_1_status}}</td>
                            <td>{{leadrock.direct_email_1}}</td>
                            <td>{{leadrock.direct_email_1_status}}</td>
                            <td>{{leadrock.direct_email_2}}</td>
                            <td>{{leadrock.direct_email_2_status}}</td>
                            <td>{{leadrock.phone_1}}</td>
                            <td>{{leadrock.phone_2}}</td>
                            <td>{{leadrock.phone_3}}</td>
                            <td>{{leadrock.phone_4}}</td>
                            <td>{{leadrock.phone_5}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>


</body>

</html>